import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const styles = StyleSheet.create({
  section: { marginBottom: 40 },
  sectionMobile: { marginBottom: 24 },
  headerRow: { marginBottom: 16 },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: 'rgba(129,86,0,0.1)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeText: { fontSize: 11, fontWeight: 'bold', color: colors.tertiary, letterSpacing: 1 },
  header: { marginBottom: 32 },
  headerMobile: { marginBottom: 20 },
  sectionTitle: { fontSize: 32, fontWeight: 'bold', color: colors.onSurface, marginBottom: 12 },
  sectionTitleMobile: { fontSize: 26, marginBottom: 8 },
  sectionDesc: { color: colors.outline, fontSize: 15, lineHeight: 22, maxWidth: 600 },
  card: {
    backgroundColor: colors.white,
    padding: 24,
    borderRadius: 16,
    gap: 28,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.02,
    shadowRadius: 20,
    elevation: 2,
  },
  backAction: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backLabel: { fontSize: 10, color: colors.slate400, letterSpacing: 2 },
  backTitle: { fontSize: 16, fontWeight: 'bold', color: colors.onSurface },
  progressSection: { gap: 10 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
  stepLabel: { fontSize: 11, fontWeight: 'bold', color: colors.cyan600 },
  stepDesc: { fontSize: 12, color: colors.slate400 },
  progressTrack: { height: 6, backgroundColor: colors.surfaceContainer, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: 6, width: '50%', borderRadius: 3 },
  tabBar: { flexDirection: 'row', gap: 24, borderBottomWidth: 1, borderBottomColor: colors.surfaceContainerHigh },
  tab: { paddingBottom: 12 },
  tabActive: { borderBottomWidth: 2, borderBottomColor: colors.cyan600 },
  tabText: { fontSize: 14, fontWeight: '600', color: colors.slate400 },
  tabTextActive: { color: colors.cyan600 },
});

