import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const styles = StyleSheet.create({
  section: { marginBottom: 40 },
  sectionMobile: { marginBottom: 24 },
  headerRow: { marginBottom: 16 },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: '#ecdcff',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeText: { fontSize: 11, fontWeight: 'bold', color: '#270057', letterSpacing: 1 },
  header: { marginBottom: 32 },
  headerMobile: { marginBottom: 20 },
  sectionTitle: { fontSize: 32, fontWeight: 'bold', color: colors.onSurface, marginBottom: 12 },
  sectionTitleMobile: { fontSize: 26, marginBottom: 8 },
  sectionDesc: { color: colors.outline, fontSize: 15, lineHeight: 22, maxWidth: 600 },
  drawer: {
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 24,
    padding: 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  profile: { marginBottom: 24 },
  profileImage: { width: 56, height: 56, borderRadius: 28, marginBottom: 12, backgroundColor: colors.surfaceContainerHighest },
  profileName: { fontSize: 20, fontWeight: 'bold', color: colors.onSurface, marginBottom: 4 },
  profileMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  proBadge: { fontSize: 11, fontWeight: 'bold', color: colors.cyan600, backgroundColor: '#e0f7fa', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  onlineText: { fontSize: 9, color: colors.slate400, letterSpacing: 2 },
  navItems: { gap: 4 },
  navItem: { flexDirection: 'row', alignItems: 'center', gap: 16, padding: 16, borderRadius: 12 },
  navItemActive: { backgroundColor: colors.white },
  navLabel: { fontSize: 16, fontWeight: '600', color: colors.slate400 },
  navLabelActive: { color: colors.onSurface, fontWeight: 'bold' },
  drawerFooter: { marginTop: 24, paddingTop: 20, borderTopWidth: 1, borderTopColor: colors.surfaceContainerHigh, gap: 8 },
  footerItem: { flexDirection: 'row', alignItems: 'center', gap: 16, paddingHorizontal: 16, paddingVertical: 8 },
  footerLabel: { fontSize: 14, color: colors.slate400 },
});

