import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const styles = StyleSheet.create({
  section: {
    marginBottom: 40,
  },
  sectionMobile: {
    marginBottom: 24,
  },
  header: {
    marginBottom: 32,
  },
  headerMobile: {
    marginBottom: 20,
  },
  sectionLabel: {
    color: colors.primary,
    fontSize: 12,
    letterSpacing: 3,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 40,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginBottom: 16,
    letterSpacing: -1,
  },
  sectionTitleMobile: {
    fontSize: 28,
    marginBottom: 10,
  },
  sectionDesc: {
    color: colors.outline,
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 600,
  },
  stack: {
    gap: 24,
    marginBottom: 40,
  },
  showcaseCard: {
    backgroundColor: colors.surfaceContainerLow,
    padding: 32,
    borderRadius: 16,
    gap: 28,
    alignItems: 'center',
    overflow: 'hidden',
  },
  showcaseCardMobile: {
    padding: 20,
    gap: 20,
  },
  showcaseLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: colors.outline,
    fontWeight: 'bold',
  },
  modalShell: {
    width: '100%',
    alignItems: 'center',
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 16,
    padding: 24,
    gap: 28,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  avatarPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    paddingVertical: 12,
  },
  avatarPanelMobile: {
    flexDirection: 'column',
    gap: 16,
  },
  selectedAvatarFrame: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,209,255,0.12)',
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedAvatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  avatarSwatchGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  avatarSwatch: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.surfaceContainerHigh,
  },
  avatarSwatchSecondary: {
    backgroundColor: 'rgba(127,4,255,0.14)',
  },
  avatarSwatchTertiary: {
    backgroundColor: 'rgba(254,177,39,0.2)',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  textAction: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
  },
  textActionLabel: {
    color: colors.outline,
    fontWeight: 'bold',
    fontSize: 14,
  },
  primaryAction: {
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryActionLabel: {
    color: colors.onPrimary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  confirmShell: {
    width: '100%',
    alignItems: 'center',
  },
  confirmCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 16,
    padding: 28,
    borderWidth: 1,
    borderColor: 'rgba(186,26,26,0.08)',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
  warningIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.errorContainer,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  confirmTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginBottom: 8,
  },
  confirmDesc: {
    fontSize: 14,
    color: colors.outline,
    lineHeight: 22,
    marginBottom: 24,
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 12,
  },
  keepButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 999,
    backgroundColor: colors.surfaceContainer,
    alignItems: 'center',
  },
  keepButtonText: {
    color: colors.onSurface,
    fontWeight: 'bold',
    fontSize: 14,
  },
  deleteButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 999,
    backgroundColor: colors.error,
    alignItems: 'center',
    shadowColor: colors.error,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 4,
  },
  deleteButtonText: {
    color: colors.onError,
    fontWeight: 'bold',
    fontSize: 14,
  },
  toastShell: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
  },
  toastPill: {
    width: '100%',
    maxWidth: 320,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 999,
    backgroundColor: colors.inverseSurface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 8,
  },
  toastInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  toastText: {
    color: colors.inverseOnSurface,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  toastStateLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 3,
    color: colors.primary,
    opacity: 0.5,
  },
});